### ISSUE TITLE
error when loading countries

### ISSUE THREAD

**Issue by fabowabohu** [covspace/pandemic-screen#1]
**Describe the bug**
Not all countries are loaded from `import\countries.csv`.
Everything is missing from line 228 onwards.

**How to reproduce**
running `python import/countries.py` leads to 

    Traceback (most recent call last):
    File ".\countries.py", line 16, in <module>
        dict = { "iso_code": row['country'], "country_name": row['name'], "lat": float(row['latitude']),"lng": float(row['longitude']) }
    ValueError: could not convert string to float:

**Expected behavior**
All countries are loaded.

**Additional information**
Error caused by "U.S. Minor Outlying Islands" not having lat. and long. attributes.
Solution1: check for missing lat. and long. attributes and skip them.
Solution2: add missing lat. and long. data

**Comment by ssitaru** [comment]
Thanks for reporting, I fixed it :)
